# Generated by Django 5.0.6 on 2024-05-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_post_is_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_banner',
            field=models.BooleanField(default=False),
        ),
    ]
